### ISSUE TITLE
Unused #include <sys/prctl.h> in main.cpp breaks the build on FreeBSD

### ISSUE THREAD

**Issue by danfe** [Stiffstream/arataga#5]
I see this `#include <sys/prctl.h>` line in `main.cpp`, which brings in Linux-specific `prctl()` call prototype, but it is now apparently not used anywhere in the program.  Consider removing this line as it breaks the build on FreeBSD (we have similar `procctl(2)` API which is differently named).

**Comment by eao197** [comment]
Thanks! The fix is in the master branch now.

**Comment by danfe** [comment]
Fixed by ec04e70, closing.
