### ISSUE TITLE
a_nameserver_interactor.cpp: error: static_assert failed when building with Clang 11

### ISSUE THREAD

**Issue by danfe** [Stiffstream/arataga#6]
When building arataga on FreeBSD with Clang 11.0.0, I hit the following three errors on the lines with `NOEXCEPT_CTCHECK_ENSURE_NOEXCEPT_STATEMENT`:
```
dns_resolver/interactor/a_nameserver_interactor.cpp:123:2: error: static_assert failed due to requirement 'noexcept(this->form_and_send_dns_udp_package(cmd->m_domain_name, cmd->m_ip_version, insertion_result.first->first, insertion_result.first->second))' "this statement is expected to be noexcept: form_and_send_dns_udp_package( cmd->m_domain_name, cmd->m_ip_version, insertion_result.first->first, insertion_result.first->second )"
        NOEXCEPT_CTCHECK_ENSURE_NOEXCEPT_STATEMENT(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./noexcept_ctcheck/pub.hpp:43:3: note: expanded from macro 'NOEXCEPT_CTCHECK_ENSURE_NOEXCEPT_STATEMENT'
                static_assert(noexcept(stmt), "this statement is expected to be noexcept: " #stmt); \
                ^             ~~~~~~~~~~~~~~
```
This does not happen when building with GCC 9.  Commenting out `NOEXCEPT_CTCHECK_ENSURE_NOEXCEPT_STATEMENT` allows the build to finish; resulting executable works fine.

**Comment by eao197** [comment]
Can you check a version from 0.5-dev branch?

**Comment by danfe** [comment]
No, I'm afraid 0ec1144 alone is not enough to fix it. :-(

**Comment by eao197** [comment]
Ok, I'll take a timeout to think about how to resolve that issue because checking the noexcept-ness of this call is essential.

**Comment by eao197** [comment]
@danfe 
Could you check another time?

**Comment by danfe** [comment]
With both patches applied, it builds fine now, thank you!  I can start packaging arataga for FreeBSD. :-)

**Comment by eao197** [comment]
Thanks for your help!

**Comment by danfe** [comment]
I was actually quite surprised how easily did it build under FreeBSD; not sure if this was part of the original TZ (техзадание), but it certainly adds to your karma.  I'd be recommending your company to anyone who seeks high-quality, portable, OS-agnostic C++ solutions.

**Comment by eao197** [comment]
> I was actually quite surprised how easily did it build under FreeBSD; not sure if this was part of the original TZ (техзадание)

No, it wasn't a part of TZ. Moreover, we had the luxury of staying within one version of a particular Linux distribution with a particular version of g++, but:

* arataga is based on highly portable libraries that were tested on different platforms;
* we knew how useful could be the use of different compilers during the development so we periodically compiled and tested arataga under g++10 and clang++10 on Linux (but with g++'s libstd++ only);
* there wasn't a need to dive into some OS-specific optimizations yet so we can stay inside the standard C++.

> I'd be recommending your company to anyone who seeks high-quality, portable, OS-agnostic C++ solutions.

Thank you very much for your kind words!
